---
title: "Customer Behavior"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    theme: readable
    source_code: embed
    navbar:
      - {title: "Data source", href: "https://www.kaggle.com/datasets/thedevastator/analyzing-customer-spending-habits-to-improve-sa", icon: "far fa-clipboard"}       
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(dplyr)
library(plotly)
library(maps)
library(ggplot2)
library(ggcorrplot)
library(tidyverse)
library(ggtext)
library(sf) 
library(rnaturalearth) 
library(countrycode) 
library(ggrepel)
library(hrbrthemes)
```


```{r data}
data <- read.csv("customerBehaviorAn.csv")
Categorical.Variables = c("Customer.Gender","Product.Category","Age.group")
Numeric.Variables = c("Customer.Age","Revenue","Margin")
reM=c("Revenue","Margin")
demograph=c("Age.group","Customer.Gender")
theme = theme_ipsum() + theme(plot.caption = element_text(hjust=0, size=8),
                                plot.title = element_text(hjust = 0, size=12, 
                                                          face="bold"),
                                axis.title.x = element_text(size=10),
                                axis.title.y = element_text(size=10))


```
# EDA
Column {.sidebar data-width=200}
-----------------------------------------------------------------------
```{r}
selectInput("categorical_variable",label ="select Categrical variable",choices = Categorical.Variables )
selectInput("numeric_variable",label = "Select Numeric Variable:",choices = Numeric.Variables)
```
Column {data-width=400}
-----------------------------------------------------------------------

### Check Outlier 

```{r}
renderPlotly({
  plot_ly(data,
              x = ~data[[input$numeric_variable]],
              color = ~data[[input$categorical_variable]],
              colors = "Paired",
              type = "box") %>%
  layout(title = "",
         xaxis = list(title = "" ,
                      zeroline = FALSE))
})

```

Column {data-width=400} 
-----------------------------------------------------------------------

### Count number of Variables

```{r}
renderPlotly({
  data %>%
    count(var = data[[input$categorical_variable]], name = "count") %>%
    plot_ly( x = ~var, y = ~ count, type = "bar", marker = list(color = '#008ae6',
                           line = list(color = '#008ae6', width = 2)), hoverinfo = "x+y") %>%
    add_text(text = ~paste0( " (",   scales::percent(count/sum(count)),")"), 
           textposition = "bottom", 
           textfont = list(size = 12, color = "white"), 
           showlegend = FALSE) %>%
    layout(xaxis = list(title = ""), yaxis = list(title = ""))
    
})

```
### Distribution of Variables 

```{r}
renderPlotly({
  plot_ly(x = data[[input$numeric_variable]], type = "histogram",  marker = list(color = "#008ae6",
                            line = list(color = "darkgray",
                                        width = 1)))
})

```

# Map


```{r map}
world <- ne_countries(scale = "small", returnclass = "sf")

data_maps <- data %>%
  select(Country) %>%
  mutate(Country = recode(Country, 
                                    "England" = "United Kingdom", 
                                    "Scotland" = "United Kingdom")) %>%
  mutate(ConuntryRetail = TRUE)

# add iso3 country code
data_with_iso <- data_maps %>%
  mutate(Iso3 = countrycode::countrycode(
    sourcevar = Country, 
    origin = "country.name", 
    destination = "iso3c")
  )



countries_Retils <- world %>%
  select(geometry, name, iso_a3) %>%
  left_join(data_with_iso, by = c("iso_a3" = "Iso3")) %>%
  filter(ConuntryRetail == TRUE)

 world %>%
  filter(admin != "Antarctica") %>%
  st_transform(crs = "+proj=robin") %>%
  ggplot() +
  geom_sf(color = "darkgrey") +
  geom_sf(data = countries_Retils, aes(fill = ConuntryRetail)) +
  scale_fill_manual(values = "royalblue") +
  theme_minimal() +
  theme(plot.title = element_text(face = "bold"),
        axis.text.x = element_blank(),
        legend.position = "none") +
  labs(title = "The Company Branch Locations",
       subtitle = "US,UK,Germany,France ",
       x = NULL, y = NULL)




```

# Analysis

Column {data-width=400}
-------------------------------------------------------------------

### **Revenue by Country** 

```{r table}
bp<- ggplot(data, aes(x="", y=Revenue, fill=Country))+
geom_bar(width = 1, stat = "identity")
pie <- bp + coord_polar("y", start=0)
pie + scale_fill_brewer(palette="Blues")+
  theme_minimal()
```

### **Margin by Country** 
```{r pieM}
# Horizontal version
ggplot(data, aes(x= Country, y= Margin)) +
  geom_segment( aes(x=Country, xend= Country, y=0, yend= Margin), color="skyblue") +
  geom_point( color="blue", size=4, alpha=0.6) +
  theme_light() +
  coord_flip() +
  theme(
    panel.grid.major.y = element_blank(),
    panel.border = element_blank(),
    axis.ticks.y = element_blank()
  )

```

Column {data-width=400} 
-------------------------------------------------------------------

### **Revenue by Month** 
```{r bar}
plotdata <- data %>%
  group_by(Month.Year) %>%
  summarize(Revenues = sum(Revenue))


pp<-ggplot(plotdata,
       aes(x= Month.Year, y=Revenues)) +
       geom_bar(stat = "identity",fill = "cornflowerblue")+
       theme_ipsum()+
       theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))
 pp     

```

### **Age Comparison by Country** 
```{r box}
pw <- ggplot(data, aes(x=Country,  color=Age.group, fill = Age.group)) +
  geom_bar() + 
  scale_fill_brewer()+
  theme_classic()+
  ylab("count")  

pw
```

# Demographic Customer Analysis

Column  {.sidebar data-width=200}
-------------------------------------------------------------------
```{r input}
radioButtons("ReMa", label = "Select :", choices = reM)

radioButtons("demograph", label = "Select:", choices = demograph)

sliderInput(inputId="bw_adjust", label ="Density plot bandwidth adjustment:",
            min =0.2, max=2, value=1, step=0.2)
```


Column  {data-width=400}
-------------------------------------------------------------------
### **Revenue, Margin by customer demographic** 

```{r dount}
renderPlotly({
  p1 = ggplot(data, aes_string(x=input$ReMa, fill=input$demograph)) +
   geom_density(alpha = 0.4, bw = input$bw_adjust) +
    theme
  
  ggplotly(p1, res=100)

})

```

Column  {data-width=400}
-------------------------------------------------------------------
### **Number of Product Category in each Age group ** 

```{r dd}
p<- ggplot(data, 
       aes(x =  Age.group, 
           fill = Product.Category)) + 
  geom_bar(color="black",position = position_dodge(preserve = "single"))
p+scale_fill_brewer(palette="Blues")
  
```

### **Number of Product Category in gender** 

```{r dbd}
p<- ggplot(data, 
       aes(x =  Customer.Gender, 
           fill = Product.Category)) + 
  geom_bar(color="black",position = position_dodge(preserve = "single"))
p+scale_fill_brewer(palette="Blues")
```
